package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (two_sets_of_rules_salience_no-loop_bonus_MODIFY)"
dialect "java"
agenda-group "two_sets_of_rules_salience_no-loop_bonus_MODIFY"
salience 200
no-loop false
when
    $uc : UniversityCandidate(olympicFinalist == true);
then
  	modify($uc) {
        setExamResult(2 * $uc.getExamResult()),
    	appendLogger("Rule 'Olympic bonus' fired!")
    }
end