package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;

// Kwalifikacja olimpijska
rule "Olympic Qualification (main)"
dialect "java"
// Reguły bez przypisanej agenda-group są przyporządkowane do domyślnej agendy 'main'!
// Agenda 'main' jest w procesie wnioskowanie ZAWSZE wywoływana tj. uzyskuje FOCUS.
// Wywołanie jest niejawne i odbywa się po jawnych wywołaniach agend.
// Aby wyłączyć automatyczne uruchamianie n/w reguły należy ją przypisać do agendy (tj. odkomentować wiersz zawierający parametr agenda-group).
// Aby wykonać testy automatycznego uruchamianie n/w reguły nie należy jej przypisywać do żandnej agendy (tj. zakomentować wiersz zawierający parametr agenda-group).
agenda-group "do_not_focus_automatically"
when
    $uc : UniversityCandidate(olympicFinalist == true);
then
    $uc.setAdmission(true);
    $uc.setQualificationType("Olympic qualification");
    $uc.appendLogger("Agenda 'Main' got focus!");
    $uc.appendLogger("Rule 'Olympic qualification' fired!");
end