package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;
import pl.edu.pwsztar.universityrecruitment.ExamSubjectResult;

// Kwalifikacja na podstawie egzaminu : Sumowanie wyniku przedmiotu egzaminacyjnego

// Informatyka
rule "Subject result summation / Informatyka (exam_result_calculation)"
dialect "java"

// Atrybuty reguły
agenda-group "exam_result_calculation"

when
	// Przesłanki
then
	// Akcje
end

// Reguły dla pozostałych kierunków
// Automatyka i robotyka
// Elektrotechnika
// Pielęgniarstwo
// Psychologia