package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;
import pl.edu.pwsztar.universityrecruitment.ExamSubjectResult;

// Kwalifikacja na podstawie egzaminu : Odczytanie kolekcji przedmiotów egzaminacyjnych
rule "Get subjects for exam qualification (exam_result_calculation)"
dialect "java"

// Atrybuty reguły
agenda-group "exam_result_calculation"

when
	// Przesłanki
then
	// Akcje
end