package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (three_sets_of_rules_salience_lock-on-active_bonus_MODIFY)"
dialect "java"
agenda-group "three_sets_of_rules_salience_lock-on-active_bonus_MODIFY"
salience 300
lock-on-active true

when
    $uc : UniversityCandidate(olympicFinalist == true);
then
  	modify($uc) {
        setExamResult(2 * $uc.getExamResult()),
    	appendLogger("Rule 'Olympic bonus' fired!")
    }
end