package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;
import pl.edu.pwsztar.universityrecruitment.ExamSubjectResult;

// Kwalifikacja na podstawie egzaminu : Mnożenie wyniku z przedmiotu 
// zdawanego na poziomie rozszerzonym przez 2
rule "Subject result multiplication on exam level (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 500

when
    $esr : ExamSubjectResult(examLevel == 'rozszerzony');
then
	modify($esr) {
  		setExamResult(2*$esr.getExamResult())
    }
  	
  	System.out.println("Modify subject result *2 " + $esr.getExamSubject());
end