package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (exam_result_calculation)"
dialect "java"
agenda-group "exam_result_calculation"
salience 200
activation-group "group-qualification"
//lock-on-active true

when
    $uc : UniversityCandidate(olympicFinalist == true);
then
	$uc.setAdmission(true);
    $uc.setQualificationType("Olympic qualification");
  	$uc.appendLogger("Rule 'Olympic qualification' fired!");

  	System.out.println("Olympic finalist " + $uc.getFirstName() + " " + $uc.getLastName());    
end