package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (two_sets_of_rules_bonus_salience_modify_lock-on-active)"
dialect "java"
agenda-group "two_sets_of_rules_bonus_salience_modify_lock-on-active"
salience 300
lock-on-active true
when
    $uc : UniversityCandidate(olympicFinalist == true);
then
	// System.out.println("Before OLYMPIC RULE examResult = " + $uc.getExamResult());
  	modify($uc) {
        setExamResult(2 * $uc.getExamResult()),
    	appendLogger("Rule 'Olympic bonus' fired!")
    }
end