package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (two_sets_of_rules_bonus_salience_modify_no-loop)"
dialect "java"
agenda-group "two_sets_of_rules_bonus_salience_modify_no-loop"
salience 200
no-loop true
when
    $uc : UniversityCandidate(olympicFinalist == true);
then
  	modify($uc) {
        setExamResult(2 * $uc.getExamResult()),
    	appendLogger("Rule 'Olympic bonus' fired!")
    }
end