package rules

import pl.edu.pwsztar.universityrecruitment.UniversityCandidate;

// Kwalifikacja olimpijska
rule "Olympic qualification (two_sets_of_rules_salience_activation-group_modify_no-loop)"
dialect "java"
agenda-group "two_sets_of_rules_salience_activation-group_modify_no-loop"
salience 200
activation-group "group-1"
no-loop true
when
    $uc : UniversityCandidate(olympicFinalist == true, counter < 10);
then
  	modify($uc) {
		setAdmission(true),
        setQualificationType("Olympic qualification"),
    	appendLogger("Rule 'Olympic qualification' fired!"),
		incrementCounter()    	
    }    
end